program: scripts/skrl/train_manual.py
command:
  - /workspace/isaaclab/_isaac_sim/python.sh
  - ${program}
  - --task=Template-Quadcopter-Hierarchical-Control-Direct-v0
  - --headless
method: bayes
metric:
  goal: minimize
  name: Info / Episode_Info/final_distance_to_goal
  
parameters:
  # Learning parameters
  learning_rate:
    values: [1e-3,1e-4,1e-5]
  
  learning_epochs:
    values: [5, 8, 10]
  
  rollouts:
    values: [32, 64, 128]
  
  # # PPO specific
  # discount_factor:
  #   values: [0.99] # non fare lo sweep mantieni 0.99
  
  entropy_loss_scale:
    values: [0.001, 0.01]

  # Reward scales
  lin_vel_reward_scale:
    values: [0.1, 1.0]

  ang_vel_reward_scale:
    values: [0.1, 1.0]

  rew_scale_action_reg:
    values: [0.0, 0.1, 5.0]
  
  distance_to_goal_reward_scale:
    values: [1.0, 10, 25, 50]
  
  alive_reward_scale:
    values: [0.1, 5.0]

  death_reward_scale:
    values: [-50, -2000]

  hidden_size:
    values: [256, 512]



