program: scripts/skrl/train_manual.py
command:
  - /workspace/isaaclab/_isaac_sim/python.sh
  - ${program}
  - --task=Template-Quadcopter-Hierarchical-Control-Direct-v0
  - --headless
method: bayes
metric:
  goal: minimize
  name: Info / Episode_Info/final_distance_to_goal
  
parameters:
  # Learning parameters
  learning_rate:
    values: [1e-5]
  
  learning_epochs:
    values: [8]
  
  rollouts:
    values: [64]
  
  # # PPO specific
  # discount_factor:
  #   values: [0.99] # non fare lo sweep mantieni 0.99
  
  entropy_loss_scale:
    values: [0.001]

  # Reward scales
  lin_vel_reward_scale:
    values: [0.1]

  ang_vel_reward_scale:
    values: [0.1]

  rew_scale_action_reg:
    values: [0.1]
  
  distance_to_goal_reward_scale:
    values: [25]
  
  alive_reward_scale:
    values: [0.1]

  death_reward_scale:
    values: [-2000]

  hidden_size:
    values: [256]



