# config.yaml
program: training_offline_sweep.py
method: random
name: sweep
metric:
  goal: minimize 
  name: val_to_minimize

# parameters:
#   beta:
#     values: [20.0, 15.0, 10.0, 5.0]

parameters:
  latent_dim:
    values: [512]
  beta_max:
    values: [400, 600, 800, 1000, 1500, 2000]


