program: scripts/skrl/train_sequential.py
command:
  - /workspace/isaaclab/_isaac_sim/python.sh
  - ${program}
  - --task=Template-Quadcopter-Direct-v0
  - --headless
method: bayes
metric:
  goal: maximize
  name: Info/Episode_Reward/distance_to_goal
parameters:
  learning_rate:
    min: 0.0001
    max: 0.001
  learning_epochs:
    values: [5, 10, 15]
  rollouts:
    values: [16, 24, 48]